---
- name: Gather EC2 facts
  action: ec2_facts

- name: Set pulic url
  set_fact: public_url="https://{{ansible_ec2_public_ipv4}}"
  when: public_url is not defined

- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  sudo: True
  with_items:
    - git
    - make
    - python-pip
    - python-dev
    - supervisor

- name: Install global python modules
  pip: name={{item}}
  sudo: True
  with_items:
    - awscli
    - virtualenv

- name: Create grits group
  user: name={{ grits_group }}

- name: Create grits user
  user: name={{ grits_user }} group={{ grits_group }} shell=/bin/bash

- name: Create grits environment configuration
  template: src=config.j2 dest=/home/{{ grits_user }}/grits_config group={{ grits_group }} owner={{ grits_user }}

- name: Create cron script directory
  file: path={{ cron_prefix }} group={{ grits_group }} owner={{ grits_user }} state=directory

- name: Create cron log directory
  file: path={{ cron_logs }} group={{ grits_group }} owner={{ grits_user }} state=directory

- name: Create github key
  copy: content="{{git_key}}" dest=~/.ssh/id_rsa mode="0700"

- stat: path=/home/grits/diagnostic-dashboard/.git
  register: indicator_git_dir

- name: Remove old non-git synced code
  file: path=/home/grits/{{item}} state=absent
  when: not (indicator_git_dir.stat.isdir is defined and indicator_git_dir.stat.isdir)
  with_items:
    - grits-api
    - grits-api-source
    - annie
    - diagnostic-dashboard
    - diagnostic-dashboard-source
    - jvm-nlp
    - jvm-nlp-source

- name: Remove old non-git synced girder code
  file: path=/opt/girder state=absent
  when: not (indicator_git_dir.stat.isdir is defined and indicator_git_dir.stat.isdir)
